version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '6379'
  bot:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      DISCORD_GUILD_ID: your_guild_id
      DISCORD_BOT_TOKEN: your_bot_token
      REDIS_ADDR: redis:6379

  bridge_comannder:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379

volumes:
  redis-data: