# docker-compose.yml
version: '3.8'
services:
  bot:
    build: .
    restart: always
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - redis-data:/data
volumes:
  redis-data:
