# kubectl -n bots expose deployment comannder --type=LoadBalancer --name=comannder
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: comannder
  name: comannder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: comannder
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: comannder
    spec:
      containers:
        - env:
            - name: REDIS_HOSTS
              value: local:redis:6379
          image: rediscommander/redis-commander:latest
          name: comannder
          ports:
            - containerPort: 8081
          resources: {}
      hostname: comannder
      restartPolicy: Always
status: {}
